// Омская область — меры поддержки семей с детьми (региональный/муниципальный бюджет).
// Источник: формы субъекта (запрос Т.В. Буцкой) — порталы министерств omskportal.ru
// и Администрации г. Омска (admomsk.gosuslugi.ru). omskportal.ru даёт SSL-ошибку
// для WebFetch → суммы 2026 сверены по gogov.ru / admomsk.gosuslugi / WebSearch.
// Запуск: node scripts/_seed-omsk.mjs
import { createClient } from "@supabase/supabase-js";
import { readFileSync } from "fs";
const env = Object.fromEntries(readFileSync(".env.local","utf8").split(/\r?\n/).filter(l=>l&&!l.startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i),l.slice(i+1)];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});

const REGION = "Омская область";
const SN = "Правительство Омской области (omskportal.ru) / Администрация г. Омска";
const MTSR = "https://mtsr.omskportal.ru/oiv/mtsr/otrasl/SOCPODDERZHKA/SocpoddershkaSemiDetey/";
const MOBR = "https://mobr.omskportal.ru/oiv/mobr/otrasl/podsem";
const MZDR = "https://mzdr.omskportal.ru/oiv/mzdr/otrasl/";
const MIO = "https://mio.omskportal.ru/oiv/mio/ZemlyaBesplatno/20140416";
const ADM = "https://admomsk.gosuslugi.ru/dlya-zhiteley/mery-podderzhki/mnogodetnye/";
const base = { level:"regional", region:REGION, updated_at_label:"2026", is_published:true, sort_order:0 };
const reg = (extra={}) => ({ regions:[REGION], ...extra });
const HOW = ["Подать заявление в орган социальной защиты (КЦСОН) по месту жительства, МФЦ или через Госуслуги"];
const DOCS = ["Паспорт заявителя","Свидетельство о рождении ребёнка","Сведения о доходах семьи (при оценке нуждаемости)"];

const rows = [
{ ...base, slug:"omsk-001",
  title:"Областной материнский (семейный) капитал (Омская область)",
  short_description:"При рождении или усыновлении третьего и последующего ребёнка семья получает областной материнский капитал.",
  category:"Выплаты и пособия",
  amount:"100 000 ₽ (ежегодно индексируется)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:HOW, documents:["Паспорт","Свидетельства о рождении детей","Сведения о месте жительства в области"],
  tips:["Право — при рождении 3-го и последующих детей с 1 января 2011 года, если ранее капитал не получали.","Направления: жильё, образование, и другие, установленные областным законом."],
  source_url:MTSR+"OMK", source_name:SN },

{ ...base, slug:"omsk-002",
  title:"Единовременное пособие при рождении двойни и более (Омская область)",
  short_description:"Семьям при одновременном рождении двух и более детей выплачивают единовременное пособие.",
  category:"Выплаты и пособия",
  amount:"10 000 ₽",
  segments:["expecting-second","expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:2 }),
  how_to_apply:HOW, documents:["Паспорт","Свидетельства о рождении детей"],
  tips:["Назначается при одновременном рождении двух и более детей."],
  source_url:MTSR+"SemyaDeti", source_name:SN },

{ ...base, slug:"omsk-003",
  title:"Ежемесячное пособие семьям с пятью и более детьми (Омская область)",
  short_description:"Семьям, воспитывающим пять и более детей, выплачивают ежемесячное пособие на каждого ребёнка.",
  category:"Выплаты и пособия",
  amount:"500 ₽/мес на каждого ребёнка (до 18 лет)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:5 }),
  how_to_apply:HOW, documents:["Паспорт","Свидетельства о рождении детей"],
  tips:["Выплачивается одному из родителей (опекунов) на каждого совместно проживающего ребёнка."],
  source_url:MTSR+"MnogodetnyeSemi", source_name:SN },

{ ...base, slug:"omsk-004",
  title:"Ежемесячное пособие студенческим семьям с детьми (Омская область)",
  short_description:"Студенческим семьям, где оба родителя учатся очно (или одинокому родителю-студенту), выплачивают ежемесячное пособие на ребёнка.",
  category:"Выплаты и пособия",
  amount:"Ежемесячное пособие на ребёнка (размер — по областному закону)",
  segments:["student-family","expecting-first","expecting-second"],
  criteria:reg({ requiresChildren:true, requiresStudent:true }),
  how_to_apply:HOW, documents:["Паспорта родителей","Справки об очном обучении","Свидетельство о рождении ребёнка"],
  tips:["Может оформить и одинокий родитель-студент очной формы."],
  source_url:MTSR+"SemyaDeti", source_name:SN },

{ ...base, slug:"omsk-005",
  title:"Единовременная выплата при рождении ребёнка студенческим семьям (Омская область)",
  short_description:"Студенческим семьям при рождении ребёнка выплачивают единовременную региональную выплату.",
  category:"Выплаты и пособия",
  amount:"Единовременная выплата (размер — по областному закону)",
  segments:["student-family","expecting-first","expecting-second","expecting-third-plus"],
  criteria:reg({ requiresChildren:true, requiresStudent:true }),
  how_to_apply:HOW, documents:["Паспорта родителей","Справки об обучении","Свидетельство о рождении ребёнка"],
  tips:["Поддержка молодых родителей, совмещающих учёбу и воспитание ребёнка."],
  source_url:MTSR+"SemyaDeti", source_name:SN },

{ ...base, slug:"omsk-006",
  title:"Выплата за медали «Материнская слава» и «Отцовская доблесть» (Омская область)",
  short_description:"Родителям, награждённым областными медалями «Материнская слава» (женщинам) или «Отцовская доблесть» (мужчинам), выплачивают единовременную денежную выплату.",
  category:"Выплаты и пособия",
  amount:"Единовременная выплата к награде (по областному закону)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:HOW, documents:["Паспорт","Удостоверение к медали","Свидетельства о рождении детей"],
  tips:["Награда — за достойное воспитание детей в многодетной семье."],
  source_url:"https://mtsr.omskportal.ru/oiv/mtsr/otrasl/SOCPODDERZHKA/SocpoddershkaKategorGrazhdan/MaterinskayaSlava", source_name:SN },

{ ...base, slug:"omsk-007",
  title:"Денежная выплата взамен земельного участка многодетным (Омская область)",
  short_description:"Многодетным семьям, стоящим на учёте на бесплатный земельный участок под ИЖС, вместо участка можно получить денежную выплату (сертификат).",
  category:"Жильё и ипотека",
  amount:"200 000 ₽ (целевая выплата на жильё)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Состоять на учёте на земельный участок; подать заявление в орган имущественных отношений / соцзащиту"],
  documents:["Паспорт","Удостоверение многодетной семьи","Документы о постановке на учёт на земельный участок"],
  tips:["Заявления принимаются до 31 августа текущего года.","Альтернатива бесплатному земельному участку."],
  source_url:MIO, source_name:SN },

{ ...base, slug:"omsk-008",
  title:"Бесплатный земельный участок многодетным семьям (Омская область)",
  short_description:"Многодетным семьям бесплатно предоставляют земельный участок для ИЖС, ведения личного подсобного хозяйства или садоводства.",
  category:"Жильё и ипотека",
  amount:"Земельный участок бесплатно (или выплата 200 000 ₽ взамен)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Встать на учёт на земельный участок в органе местного самоуправления / имущественных отношений"],
  documents:["Паспорт","Удостоверение многодетной семьи","Свидетельства о рождении детей"],
  tips:["Вместо участка можно выбрать денежную выплату."],
  source_url:MIO, source_name:SN },

{ ...base, slug:"omsk-009",
  title:"Социальные выплаты молодым семьям на жильё (Омская область)",
  short_description:"Молодым семьям предоставляют социальную выплату на приобретение или строительство жилья, в том числе на первоначальный взнос по ипотеке.",
  category:"Жильё и ипотека",
  amount:"Не менее 35 % расчётной (средней) стоимости жилья",
  segments:["expecting-first","expecting-second","expecting-third-plus"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Встать в очередь на участие в программе «Молодая семья» через администрацию / Минстрой области"],
  documents:["Паспорта супругов","Свидетельства о рождении детей","Документы о нуждаемости в жилье"],
  tips:["Можно направить на первоначальный взнос по ипотеке."],
  source_url:"https://mszhk.omskportal.ru/oiv/mszhk/otrasl/upravl-fcp-gilisch/gos_podder/molodaj_sem-ja", source_name:SN },

{ ...base, slug:"omsk-010",
  title:"Социальная выплата семьям с 3+ детьми на строительство дома (Омская область)",
  short_description:"Семьям, имеющим трёх и более детей, предоставляют социальную выплату на строительство индивидуального жилого дома.",
  category:"Жильё и ипотека",
  amount:"Социальная выплата на строительство дома (по программе области)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Подать заявление через Минстрой области / администрацию"],
  documents:["Паспорт","Удостоверение многодетной семьи","Документы на земельный участок и строительство"],
  tips:["Помощь именно на индивидуальное жилищное строительство."],
  source_url:"https://mszhk.omskportal.ru/oiv/mszhk/otrasl/upravl-fcp-gilisch/gos_podder/mnogodetn", source_name:SN },

{ ...base, slug:"omsk-011",
  title:"Жильё коммерческого фонда многодетным со скидкой (г. Омск)",
  short_description:"Многодетным семьям предоставляют жильё из коммерческого жилищного фонда со скидкой на плату за наём.",
  category:"Жильё и ипотека",
  amount:"Скидка 40 % на плату за наём; срок найма — 5 лет",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Обратиться в Администрацию г. Омска (управление социальных вопросов)"],
  documents:["Паспорт","Удостоверение многодетной семьи","Документы о нуждаемости в жилье"],
  tips:["Подходит семьям, которым нужно временное жильё на льготных условиях."],
  source_url:ADM, source_name:SN },

{ ...base, slug:"omsk-012",
  title:"Компенсация расходов на содержание лифтов (г. Омск)",
  short_description:"Малоимущим, одиноким матерям и многодетным семьям, живущим на первых этажах домов с лифтами, компенсируют расходы на содержание и ремонт лифтов.",
  category:"Жильё и ипотека",
  amount:"100 % компенсации (без других мер) или 50 % (при наличии иной поддержки)",
  segments:["expecting-third-plus","single-parent"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Подать заявление в Администрацию г. Омска / соцзащиту"],
  documents:["Паспорт","Документы на жильё","Документы о составе семьи и доходах"],
  tips:["Касается жильцов первых этажей домов, оборудованных лифтами."],
  source_url:ADM, source_name:SN },

{ ...base, slug:"omsk-013",
  title:"Бесплатное горячее питание школьников 5–11 классов из многодетных семей (Омская область)",
  short_description:"Детям из многодетных семей, обучающимся в 5–11 классах, предоставляют бесплатное ежедневное горячее питание.",
  category:"Образование",
  amount:"Бесплатно (около 60 ₽ в день)",
  segments:["schoolchild","expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Подать заявление в школу"],
  documents:["Паспорт","Удостоверение многодетной семьи","Справка об обучении"],
  tips:["Дополняет федеральное бесплатное питание для учеников 1–4 классов."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-014",
  title:"Льгота по родительской плате за детский сад многодетным (г. Омск)",
  short_description:"Многодетным семьям снижают плату за присмотр и уход за детьми в детском саду.",
  category:"Образование",
  amount:"Сниженная родительская плата (70 % от установленного размера)",
  segments:["expecting-third-plus"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Подать заявление в детский сад / департамент образования"],
  documents:["Паспорт","Удостоверение многодетной семьи","Договор с детским садом"],
  tips:["Отдельно действует федеральная компенсация части родительской платы (20/50/70 %)."],
  source_url:ADM, source_name:SN },

{ ...base, slug:"omsk-015",
  title:"Компенсация части стоимости обучения детей в колледжах области (Омская область)",
  short_description:"Семьям компенсируют часть стоимости обучения детей в государственных профессиональных образовательных организациях области.",
  category:"Образование",
  amount:"Компенсация части стоимости обучения (по областному порядку)",
  segments:["schoolchild","expecting-third-plus"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Подать заявление через образовательную организацию / Минобразования области"],
  documents:["Паспорт","Договор об обучении","Документы о льготной категории"],
  tips:["Касается обучения в государственных колледжах (СПО) области."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-016",
  title:"Компенсация затрат на обучение ребёнка-инвалида на дому (Омская область)",
  short_description:"Родителю ребёнка-инвалида, обучение которого организовано на дому, компенсируют затраты на обучение.",
  category:"Образование",
  amount:"Компенсация затрат на надомное обучение (по нормативам области)",
  segments:["disability"],
  criteria:reg({ requiresChildren:true, requiresDisabledChild:true }),
  how_to_apply:["Подать заявление в образовательную организацию / Минобразования области"],
  documents:["Паспорт законного представителя","Справка об инвалидности ребёнка","Заключение о надомном обучении"],
  tips:["Положена одному из родителей (законных представителей)."],
  source_url:"https://mobr.omskportal.ru/oiv/mobr/otrasl/obuchenie-dom", source_name:SN },

{ ...base, slug:"omsk-017",
  title:"Первоочередной приём в детские сады льготным категориям (Омская область)",
  short_description:"Детям из ряда категорий предоставляют первоочередное или внеочередное право зачисления в детские сады: детям-инвалидам, детям из многодетных семей, детям военнослужащих и сотрудников силовых органов, детям погибших участников СВО и др.",
  category:"Образование",
  amount:"Первоочередное / внеочередное зачисление в детский сад",
  segments:["expecting-third-plus","disability","svo-family","single-parent"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Указать льготу при подаче заявления в детский сад через Госуслуги / департамент образования"],
  documents:["Паспорт","Свидетельство о рождении ребёнка","Документ, подтверждающий льготную категорию"],
  tips:["Также действует преимущественное право для братьев и сестёр (в тот же сад)."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-018",
  title:"Приём в школы льготным категориям, в т.ч. детям участников СВО (Омская область)",
  short_description:"Внеочередное и первоочередное право приёма в школы (включая школы с интернатом) имеют дети военнослужащих и добровольцев СВО, дети сотрудников силовых органов и др. категории.",
  category:"Образование",
  amount:"Внеочередное / первоочередное зачисление в школу",
  segments:["svo-family","schoolchild"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Указать льготу при подаче заявления в школу"],
  documents:["Паспорт","Документы, подтверждающие льготную категорию","Свидетельство о рождении ребёнка"],
  tips:["Распространяется и на усыновлённых, и на детей под опекой в таких семьях.","Преимущественное право — для братьев и сестёр в одну школу."],
  source_url:"https://admomsk.gosuslugi.ru/ofitsialno/struktura-munitsipalnogo-obrazovaniya/administratsiya-goroda-omska/strukturnye-podrazdeleniya/departament-obrazovaniya/normativno-pravovye-akty/", source_name:SN },

{ ...base, slug:"omsk-019",
  title:"Путёвки и проезд детям-сиротам на отдых и оздоровление (Омская область)",
  short_description:"Детям-сиротам и детям без попечения родителей предоставляют путёвки в организации отдыха и оздоровления (санатории — по медпоказаниям), а также оплачивают проезд к месту лечения и обратно.",
  category:"Культура и отдых",
  amount:"Бесплатные путёвки + оплата проезда",
  segments:["foster-family"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Обратиться через орган опеки / Минобразования области"],
  documents:["Документ о статусе ребёнка-сироты / без попечения","Документы законного представителя","Медицинские документы (для санатория)"],
  tips:["Санаторно-курортные путёвки — при наличии медицинских показаний."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-020",
  title:"Первоочередные путёвки детям из многодетных семей (Омская область)",
  short_description:"Дети из многодетных семей до 18 лет в первоочередном порядке обеспечиваются путёвками в организации отдыха и оздоровления (санатории — по медпоказаниям).",
  category:"Культура и отдых",
  amount:"Первоочередное предоставление путёвок (по квотам)",
  segments:["expecting-third-plus","schoolchild"],
  criteria:reg({ requiresChildren:true, minChildren:3 }),
  how_to_apply:["Обратиться в орган соцзащиты / Минобразования области"],
  documents:["Паспорт","Удостоверение многодетной семьи","Медицинские документы (для санатория)"],
  tips:["Хорошая возможность оздоровить детей в каникулы."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-021",
  title:"Оздоровление детей участников и ветеранов боевых действий (Омская область)",
  short_description:"Дети ветеранов и участников боевых действий имеют право на летнее оздоровление; детям участников СВО компенсируют стоимость путёвки в лагеря области.",
  category:"Культура и отдых",
  amount:"Бесплатное оздоровление / компенсация стоимости путёвки",
  segments:["svo-family"],
  criteria:reg({ requiresChildren:true, requiresSvoFamily:true }),
  how_to_apply:["Обратиться в орган соцзащиты / Минобразования области"],
  documents:["Паспорт законного представителя","Документы, подтверждающие статус участника боевых действий","Свидетельство о рождении ребёнка"],
  tips:["До 15 лет — летнее оздоровление раз в год; до 18 лет — санаторий по медпоказаниям."],
  source_url:MOBR, source_name:SN },

{ ...base, slug:"omsk-022",
  title:"Льготное обеспечение лекарствами и медизделиями (Омская область)",
  short_description:"Отдельным категориям детей и детям с определёнными заболеваниями бесплатно или со скидкой предоставляют лекарства и медицинские изделия при амбулаторном лечении.",
  category:"Здоровье",
  amount:"Бесплатно или со скидкой (по рецепту)",
  segments:["disability","expecting-first"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Получить рецепт у врача и обратиться в аптеку, отпускающую льготные лекарства"],
  documents:["Полис ОМС","Льготный рецепт","Документы о льготной категории / заболевании"],
  tips:["Перечень категорий и заболеваний устанавливается областью."],
  source_url:MZDR+"inf-family", source_name:SN },

{ ...base, slug:"omsk-023",
  title:"Бесплатное детское питание: молочная смесь, творог, кисломолочные продукты (Омская область)",
  short_description:"Детей раннего возраста бесплатно обеспечивают сухой адаптированной молочной смесью, кисломолочными продуктами и творогом.",
  category:"Здоровье",
  amount:"Бесплатно (по назначению врача)",
  segments:["expecting-first","expecting-second","expecting-third-plus"],
  criteria:reg({ requiresChildren:true, maxYoungestChildAgeYears:3 }),
  how_to_apply:["Получить назначение у педиатра и обратиться в пункт выдачи детского питания"],
  documents:["Полис ОМС","Свидетельство о рождении ребёнка","Назначение врача"],
  tips:["Аналог молочной кухни — для детей раннего возраста."],
  source_url:MZDR+"med-deti", source_name:SN },

{ ...base, slug:"omsk-024",
  title:"Денежные средства на содержание детей под опекой (Омская область)",
  short_description:"Опекунам (попечителям) выплачивают денежные средства на содержание подопечных детей, в том числе достигших 18 лет и обучающихся очно в школе.",
  category:"Выплаты и пособия",
  amount:"Ежемесячные средства на содержание подопечного ребёнка (по областному закону)",
  segments:["foster-family"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Обратиться в орган опеки и попечительства / Администрацию г. Омска"],
  documents:["Паспорт","Документы об установлении опеки / попечительства","Свидетельство о рождении ребёнка"],
  tips:["Выплата продолжается и после 18 лет, если ребёнок учится очно в школе."],
  source_url:"https://admomsk.gosuslugi.ru/dlya-zhiteley/mery-podderzhki/", source_name:SN },

{ ...base, slug:"omsk-025",
  title:"Бесплатные занятия спортом для многодетных и семей участников СВО (Омская область)",
  short_description:"Многодетным семьям — бесплатное посещение спортобъектов области раз в месяц; детям и членам семей участников СВО — бесплатные спортивные секции и посещение спортобъектов.",
  category:"Культура и отдых",
  amount:"Бесплатное посещение спортивных организаций области",
  segments:["expecting-third-plus","svo-family"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Обратиться в спортивную организацию, подведомственную области, с подтверждающими документами"],
  documents:["Паспорт","Удостоверение многодетной семьи / документы участника СВО"],
  tips:["Многодетным — раз в месяц; детям участников СВО — занятия по программам спортивной подготовки бесплатно."],
  source_url:"https://mdms.omskportal.ru/oiv/mdms/mnogodet_sem/2017-04-12-1500", source_name:SN },

{ ...base, slug:"omsk-026",
  title:"Помощь вещами многодетным, малоимущим и пострадавшим от ЧС (г. Омск)",
  short_description:"Членам многодетных и малоимущих семей, а также семьям, пострадавшим от чрезвычайных ситуаций (пожар, наводнение), предоставляют подержанные вещи и другие материальные ценности.",
  category:"Помощь и сопровождение",
  amount:"Натуральная помощь (вещи, предметы первой необходимости)",
  segments:["expecting-third-plus","single-parent"],
  criteria:reg({ requiresChildren:true }),
  how_to_apply:["Обратиться в Администрацию г. Омска / учреждение соцобслуживания"],
  documents:["Паспорт","Документы о составе семьи","Документы о ЧС (при наличии)"],
  tips:["Помогает быстро восстановить быт после пожара или наводнения."],
  source_url:"https://admomsk.gosuslugi.ru/dlya-zhiteley/mery-podderzhki/", source_name:SN },
];

let ok=0, fail=0;
for (const r of rows){
  const { error } = await sb.from("measures").upsert(r, { onConflict:"slug" });
  if(error){ console.log("FAIL", r.slug, "-", error.message); fail++; }
  else { console.log("OK  ", r.slug, "—", r.title.slice(0,56)); ok++; }
}
console.log(`\nDONE: ${ok} upserted, ${fail} failed`);
const { count } = await sb.from("measures").select("*",{count:"exact",head:true}).eq("region",REGION);
console.log("ОМСКАЯ ОБЛАСТЬ В БАЗЕ ТЕПЕРЬ:", count);
